# Generated by Django 4.1.6 on 2023-10-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_remove_whatsapp_url_whatsapp_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
