# Generated by Django 4.1.6 on 2024-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsapp_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='group',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
