version: "3.9"

services:
    pgdatabase:
        build:
            context: .
            dockerfile: ./Docker/postgres/Dockerfile
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        expose:
            - 5432
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/:rw
    django:
        build:
            context: .
            dockerfile: ./Docker/django/Dockerfile
        expose:
        - 8000
        depends_on:
        - pgdatabase
    nginx:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        ports:
            - 80:80
        depends_on:
            - django
volumes:
    pgdata:
