version: "3.9"

services:
    pgdatabase:
        image: postgres:15.1-alpine
        env_file:
            - Docker/postgres/env
        expose:
            - 5432
        restart: always
        volumes:
            - pgdatabase:/var/lib/postgresql/data/:rw
    djangoapp:
        image: djangoapp
        build:
            context: .
            dockerfile: ./Docker/django/Dockerfile
        env_file:
            - Docker/django/env
        expose:
            - 8000
        depends_on:
            - pgdatabase
            - celery
        command: /app/Docker/django/run_django.sh
    redis:
        image: redis
        expose:
            - 6379
    celery:
        restart: always
        image: djangoapp
        env_file:
            - Docker/django/env
        depends_on:
            - pgdatabase
            - redis
        command: /app/Docker/django/run_celery_worker.sh
    nginx:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        ports:
            - 80:80
        depends_on:
            - django
            - celery
volumes:
    pgdatabase:
