version: "3.9"

services:
    pgdatabase:
        image: postgres:15.1-alpine
        env_file:
            - ./Docker/postgres/.env
        expose:
            - 5432
        restart: always
        volumes:
            - pgdatabase:/var/lib/postgresql/data/:rw
    django:
        image: wap
        build:
            context: .
            dockerfile: ./Docker/django/Dockerfile
        env_file:
            - ./Docker/django/.env
        expose:
            - 8000
        depends_on:
            - pgdatabase
            - celery
        command: gunicorn wapico.wsgi:application --bind 0.0.0.0:8000
    nginx:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        ports:
            - 80:80
        depends_on:
            - django
    redis:
        image: redis
        expose:
            - 6379
    celery:
        restart: always
        image: wap
        depends_on:
            - pgdatabase
            - redis
        command: celery -A wapico.celery worker -l info
volumes:
    pgdatabase:
