version: "3.9"

services:
    pgdatabase:
        build:
            context: .
            dockerfile: ./Docker/postgres/Dockerfile
        expose:
            - 5432
        restart: always
        volumes:
            - pgdatabase:/var/lib/postgresql/data/:rw
    django:
        build:
            context: .
            dockerfile: ./Docker/django/Dockerfile
        expose:
        - 8000
        depends_on:
        - pgdatabase
        - celery
    nginx:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        ports:
            - 80:80
        depends_on:
            - django
    redis:
        image: redis
        expose:
            - 6379
    celery:
        restart: always
        build:
            context: .
            dockerfile: ./Docker/celery/Dockerfile
        depends_on:
            - pgdatabase
            - redis

volumes:
    pgdatabase:
