version: "3.9"

services:
    pgdatabase:
        build:
            context: .
            dockerfile: ./Docker/postgres/Dockerfile
        expose:
            - 5432
        restart: always
        volumes:
            - pgdatabase:/var/lib/postgresql/data/:rw
    django:
        build:
            context: .
            dockerfile: ./Docker/django/Dockerfile
        expose:
        - 8000
        depends_on:
        - pgdatabase
        - celery
#        volumes:
#            - django:/app:rw
    nginx:
#        build:
#            context: .
#            dockerfile: ./Docker/nginx/Dockerfile
        image: nginx
        environment:
            - BASIC_USERNAME = tork
            - BASIC_PASSWORD = issledur
            - FORWARD_HOST = django
            - FORWARD_PORT = 8000
        ports:
            - 80:80
        depends_on:
            - django
    redis:
        image: redis
        expose:
            - 6379
    celery:
        restart: always
        build:
            context: .
            dockerfile: ./Docker/celery/Dockerfile
#        volumes:
#            - django:/app:rw
        environment:
            - DB_HOST=pgdatabase
            - DB_NAME=wapico
            - DB_USER=wapico
            - DB_PASS=wapico
            - CELERY_BROKER_URL=redis://redis:6379
        depends_on:
            - pgdatabase
            - redis

volumes:
    pgdatabase:
#    django:
