# Generated by Django 4.1.5 on 2023-03-27 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('crontabschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.crontabschedule')),
                ('time_from', models.IntegerField(help_text='Set time period end (in seconds)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            bases=('django_celery_beat.crontabschedule',),
        ),
    ]
