# Generated by Django 4.1.5 on 2023-02-03 18:51
from django.core.management import call_command
from django.db import migrations, models


def load_initial_data(apps, schema_editor):
    # Load the fixture data for the Person model
    fixture_path = 'wapico/var/fixtures/var_init.json'
    call_command('loaddata', fixture_path)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RunPython(load_initial_data),
    ]
