# Generated by Django 4.1.5 on 2023-02-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
