# Generated by Django 4.1.5 on 2023-02-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var', '0002_alter_var_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='value',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
